name: Pipeline_deploy_front_prod_2

on:
  workflow_dispatch:
    inputs:
      number_version_project:
        description: 'Project number'
        required: false

jobs:
  deploy_kube:
    runs-on: ubuntu-latest
    steps:
    # https://github.com/actions/checkout
      - name: Init Checkout
        uses: actions/checkout@v4

      - name: Install kube
        run: |
          sudo apt-get update && sudo apt-get install -y apt-transport-https
          curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
          echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
          sudo apt-get update && sudo apt-get install -y kubectl

      - name: Kube's version    
        run : kubectl version --client

      - name: Configure kubectl configuration
        run : echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml

      - name: Deploy
        run : kubectl apply -f ./kube/front-devops-deployment.yaml --kubeconfig=kubeconfig.yaml -n 4al2-the-avengers

      - name: If error, delete resources
        if: ${{ failure() }}
        run: kubectl delete -f ./kube/front-devops-deployment.yaml --kubeconfig=kubeconfig.yaml -n 4al2-the-avengers

      - name: Verify Deployment Status
        run: kubectl get pods --kubeconfig=kubeconfig.yaml -n 4al2-the-avengers  